from manim import *

class Limites(Scene):
    def construct(self):
        
        limite1 = MathTex(r"\lim_{x \to +\infty} \frac{f(x)}{g(x)}")
        limite2 = MathTex(r"\lim_{x \to +\infty} f(x) = \lim_{x \to +\infty} g(x) = 0")
        vector=1*UP+3*LEFT
        limite1.move_to(ORIGIN+vector)
        limite2.next_to(limite1, DOWN).align_to(limite1,LEFT)
        limite3 = MathTex(r"\lim_{t \to 0^{+}} \frac{f\left(\frac{1}{t}\right)}{g\left(\frac{1}{t}\right)}").move_to(limite1)
        limite4 = MathTex(r"\lim_{t \to 0^{+}} f\left(\frac{1}{t}\right) = \lim_{t \to 0^{+}} g\left(\frac{1}{t}\right)").nnext_to(limite3, DOWN).align_to(limite3,LEFT)
        limite5 = MathTex(r"\frac{d}{dt} f\left(\frac{1}{t}\right) = \frac{d}{dt} g\left(\frac{1}{t}\right) = \frac{-\frac{1}{t^{2}} f'\left(\frac{1}{t}\right)}{-\frac{1}{t^{2}} g'\left(\frac{1}{t}\right)} = \frac{f'\left(x\right)}{g'\left(x\right)}").move_to(ORIGIN)
        limite6 = MathTex(r"\lim_{x \to +\infty} \frac{f(x)}{g(x)} = \lim_{t \to 0^{+}} g\left(\frac{1}{t}\right) = \lim_{x \to +\infty} \frac{f'(x)}{g'(x)}").move_to(limite5)
        limite7 = MathTex(r"\lim_{x \to +\infty} \frac{f(x)}{g(x)} = \lim_{x \to +\infty} \frac{f'(x)}{g'(x)}").move_to(limite6)
        texto_normal = Tex(r"siempre que exista y ",color=YELLOW)
        texto_ecuacion = MathTex(r"\lim_{x \to +\infty} f(x) = \lim_{x \to +\infty} g(x) = 0", color=YELLOW)
        full_text = VGroup(texto_normal, texto_ecuacion).arrange(RIGHT)
        full_text.next_to(limite7, DOWN).align_to(limite7, ORIGIN)
        texto1 = Tex(r"De manera similar... ",color=YELLOW).to_edge(LEFT+UP)
        texto1.shift(DOWN * 1.0)
        limite8 = MathTex(r"\lim_{x \to -\infty} \frac{f(x)}{g(x)} = \lim_{x \to -\infty} \frac{f'(x)}{g'(x)}").move_to(limite7)
        texto_e1 = MathTex(r"\lim_{x \to -\infty} f(x) = \lim_{x \to -\infty} g(x) = 0", color=YELLOW)
        full_t = VGroup(texto_normal, texto_e1).arrange(RIGHT)
        full_t.next_to(limite7, DOWN).align_to(limite7, ORIGIN)
        cuadro = SurroundingRectangle(limite7, color=YELLOW)
        
        self.play(Write(limite1))
        self.wait(1)
        self.play(Write(limite2))
        self.wait(1)
        self.play(ReplacementTransform(limite1,limite3))
        self.wait(2)
        self.play(ReplacementTransform(limite2,limite4))
        self.wait(2)
        self.play(FadeOut(VGroup(limite3,limite4)))
        self.wait(1)
        self.play(Write(limite5))
        self.wait(2)
        self.play(ReplacementTransform(limite5,limite6))
        self.wait(2)
        self.play(ReplacementTransform(limite6,limite7))
        self.wait(2)
        self.play(Create(cuadro))
        self.wait(2)
        self.play(Write(full_text))
        self.wait(2)
        self.play(Write(texto1))
        self.wait(2)
        self.play(ReplacementTransform(limite7,limite8))
        self.wait(2)
        self.play(ReplacementTransform(full_text,full_t))
        self.wait(2)
class octavio(Scene):
    def construct(self):
         texto1 = Tex(r"Calcule, de existir, el siguiente límite. ",color=YELLOW).to_edge(UP)
         limite1=MathTex(r"\lim_{x \to +\infty} xsen\left(\frac{1}{x}\right)").next_to(texto1,DOWN)
         nfinito = MathTex(r"\infty", color=PURPLE).move_to(limite1).shift(LEFT*0.3)
         cero= MathTex(r"0", color=PURPLE).next_to(nfinito,RIGHT)
         grupito=VGroup(nfinito,cero)
         limite2=MathTex(r"\lim_{x \to +\infty} x = +\infty ").next_to(grupito,LEFT).shift(DOWN*2)
         limite3=MathTex(r"\lim_{x \to +\infty} sen\left(\frac{1}{x}\right) = 0").next_to(limite2,DOWN).align_to(limite2,LEFT)
         texto=MathTex(r"\iff \lim_{x \to +\infty} \frac{1}{x} = 0" , color=YELLOW).next_to(VGroup(limite2,limite3),RIGHT).shift(UP*1/2)
         limite4=MathTex(r"xsen\left(\frac{1}{x}\right) = \frac{sen\left(\frac{1}{x}\right)}{\frac{1}{x}", color=YELLOW)
         division= MathTex(r" \implies \frac{0}{0}").next_to(limite4,RIGHT)
         limite5= MathTex(r"\lim_{x \to +\infty} xsen\left(\frac{1}{x}\right) = \lim_{x \to +\infty} \frac{sen\left(\frac{1}{x}\right)}{\frac{1}{x}}").move_to(ORIGIN).shift(UP)
         limite6= MathTex(r"= \lim_{x \to +\infty} cos\left(\frac{1}{x}\right)").next_to(limite5,DOWN).align_to(limite5,RIGHT).shift(0.1*RIGHT)
         limite7=MathTex(r"=cos(0)").move_to(limite6).align_to(limite6,LEFT)
         self.play(Write(texto1))
         self.wait(2)
         self.play(Write(limite1))
         self.wait(2)
         self.play(ReplacementTransform(limite1,grupito))
         self.wait(2)
         self.play(Write(VGroup(limite2,limite3)))
         self.wait(2)
         self.play(Write(texto))
         self.wait(2)
         self.play(FadeOut(VGroup(texto1,grupito,texto,limite2,limite3)))
         self.wait(2)
         self.play(Write(VGroup(limite4,division).move_to(ORIGIN)))
         self.wait(2)
         self.play(FadeOut(VGroup(limite4,division)))
         self.wait(2)
         self.play(Write(limite5))
         self.wait(2)
         self.play(Write(limite6))
         self.wait(2)
         self.play(ReplacementTransform(limite6,limite7))
         self.wait(2)
class baka(Scene):
    def construct(self):
         texto1 = Tex(r"Calcule el siguiente límite. ",color=YELLOW).to_edge(UP)
         limite1=MathTex(r"\lim_{x \to +\infty} \frac{x}{x-sen(x)}").next_to(texto1,DOWN).shift(0.5*DOWN)
         limite2=MathTex(r"\frac{\frac{d}{dx} x}{\frac{d}{dx}(x-sen(x))}=").next_to(limite1,DOWN).shift(LEFT+DOWN)
         limite3=MathTex(r"\frac{1}{1-cos(x)}").next_to(limite2,RIGHT).align_to(limite2)
         cuadro = SurroundingRectangle(limite3, color=PURPLE)
         texto=Tex(r"no existe el \\ $\lim x \to +\infty$" , color=PURPLE).next_to(limite3,RIGHT)
         limite4=MathTex(r"1").move_to(limite1)
         limite5= MathTex(r" \lim_{x \to +\infty} \frac{x}{x-sen(x)}=").move_to(limite2)
         limite6= MathTex(r"\lim_{x \to +\infty} \frac{1}{1-\frac{sen(x)}{x}}").next_to(limite5,RIGHT)
         self.play(Write(texto1))
         self.wait(2)
         self.play(Write(limite1))
         self.wait(2)
         self.play(Write(VGroup(limite2,limite3)))
         self.wait(2)
         self.play(Create(cuadro))
         self.wait(2)
         self.play(Write(texto))
         self.wait(2)
         self.play(FadeOut(VGroup(cuadro,texto)))
         self.wait(2)
         self.play(ReplacementTransform(limite1,limite4))
         self.wait(2) 
         self.play(ReplacementTransform(VGroup(limite2,limite3),VGroup(limite5,limite6).shift(LEFT)))
         self.wait(2)
class sueño(Scene):
    def construct(self):
         texto1 = Tex(r"La regla de L'Hopital también \\ es válida en los casos que ",color=BLUE).to_edge(LEFT).shift(2*UP)
         limite1=MathTex(r"|\lim_{x \to c} f(x)|=|\lim_{x \to c} g(x)|= \infty",color=YELLOW).next_to(texto1,DOWN).shift(4*RIGHT)
         palabra=Tex(r"y")
         palabra2=MathTex(r"\lim_{x \to c} \frac{f'(x)}{g'(x)}").next_to(palabra,RIGHT)
         palabra3=Tex(r" existe, entonces" ).next_to(palabra2, RIGHT)
         palabra.add(palabra2,palabra3).next_to(limite1,DOWN)
         limite3=MathTex(r"\lim_{x \to c}\frac{f(x)} {g(x)}=\lim_{x \to c}\frac{f'(x)}{g'(x)}", color=YELLOW).next_to(palabra,DOWN).align_to(ORIGIN)
         self.play(Write(texto1))
         self.wait(2)
         self.play(Write(limite1))
         self.wait(2)
         self.play(Write(palabra))
         self.wait(2)
         self.play(Write(limite3))
         self.wait(2)
class quinta(Scene):
    def construct(self):
        texto1 = Tex(r"Calcule, de ser posible, el siguiente límite. ",color=YELLOW).to_edge(UP)
        limite1=MathTex(r"\lim_{x \to +\infty} (ln(x)-x)").next_to(texto1,DOWN).align_to(ORIGIN).shift(DOWN)
        limite2=MathTex(r"\lim_{x \to +\infty} ln(x) = +\infty").next_to(limite1 ,DOWN).shift(DOWN)
        limite3=MathTex(r"\lim_{x \to +\infty} x = +\infty").next_to(limite2,DOWN).shift(DOWN)
        infinitos= MathTex(r"+\infty -\infty").move_to(limite1)
        limite4= MathTex(r"ln(x)-x = x \left(\frac{ln(x)}{x}-1\right)").move_to(infinitos).align_to(ORIGIN)
        limite5=MathTex(r"\lim_{x \to +\infty} \frac{ln(x)}{x} ", color=YELLOW).next_to(limite4,DOWN).shift(DOWN)
        limite6=MathTex(r"\lim_{x \to +\infty} \frac{+\infty}{+\infty}", color=YELLOW).next_to(limite4,DOWN).shift(DOWN)
        limite7=MathTex(r"\lim_{x \to +\infty} \frac{ln(x)}{x} = \lim_{x \to +\infty} \frac{\frac{1}{x}}{1}", color=YELLOW).next_to(limite4,DOWN).shift(DOWN)
        limite8=MathTex(r"\lim_{x \to +\infty} \frac{ln(x)}{x} = \lim_{x \to +\infty} \frac{1}{x} = 0", color=YELLOW).next_to(limite4,DOWN).shift(DOWN)
        limite9=MathTex(r"\lim_{x \to +\infty} (ln(x)-x) =\lim_{x \to +\infty} x \left(\frac{ln(x)}{x}-1\right) ").move_to(limite4).align_to(ORIGIN)
        limite10=MathTex(r"=\lim_{x \to +\infty} x \lim_{x \to +\infty} \left(\frac{ln(x)}{x}-1\right)").next_to(limite9,DOWN).shift(2.6*RIGHT)
        limite11=MathTex(r"=(+\infty)(0-1)").next_to(limite10,DOWN).shift(1.6*LEFT)
        limite12=MathTex(r"= -\infty").next_to(limite10,DOWN).shift(2.5*LEFT)
        self.play(Write(texto1))
        self.wait(2)
        self.play(Write(limite1))
        self.wait(2)
        self.play(Write(limite2))
        self.wait(2)
        self.play(Write(limite3))
        self.wait(2)
        self.play(FadeOut(VGroup(limite2,limite3)))
        self.wait(1)
        self.play(ReplacementTransform(limite1,infinitos))
        self.wait(2)
        self.play(FadeOut(infinitos))
        self.wait(2)
        self.play(FadeOut(texto1))
        self.wait(1)
        self.play(Write(limite4))
        self.wait(2)
        self.play(Write(limite5))
        self.wait(2)
        self.play(ReplacementTransform(limite5, limite6))
        self.wait(2)
        self.play(ReplacementTransform(limite6, limite7))
        self.wait(2)
        self.play(ReplacementTransform(limite7, limite8))
        self.wait(2)
        self.play(FadeOut(limite8))
        self.wait(2)
        self.play(ReplacementTransform(limite4,limite9))
        self.wait(1)
        self.play(Write(limite10))
        self.wait(2)
        self.play(Write(limite11))
        self.wait(2)
        self.play(ReplacementTransform(limite11,limite12))
        self.wait(2)

