from manim import *
from sklearn.linear_model import LinearRegression

def disc(axes, *point):
    c= Circle(radius=0.08, color = BLACK, fill_opacity=1, stroke_width = 1).move_to(axes.c2p(point[0], point[1]))
    d= Circle(radius=0.08, color = WHITE, stroke_width = 1.2).move_to(axes.c2p(point[0], point[1]))
    return VGroup(c,d)




class E1(Scene):
    def construct(self):
        axes = Axes(x_range=(-1,10,1),
                  y_range=(-1,20,1),
                  axis_config={"include_numbers": False, "include_tip": False}).shift(0.5*LEFT)

        x = np.arange(1,10,1,dtype=float)
        y = np.array([1.52246106, 6.2760993, 3.80538691, 6.19722876,
                      7.21630459, 11.43284789, 11.8475795, 10.04278697, 16.15779999])
        y[:] = y[::-1]
        points = VGroup(*[Dot(axes.c2p(_x,_y), color=BLUE) for _x,_y in zip(x,y)])
        points_labels = VGroup(*[MathTex(fr"a_{i+1}").scale(0.5).next_to(points[i], RIGHT) for i in range(len(points))])

        fit = LinearRegression().fit(x.reshape(-1, 1), y)
        m_ottimo = fit.coef_.flatten()[0]
        b_ottimo = fit.intercept_.flatten()[0]
        m = ValueTracker(m_ottimo)
        b = ValueTracker(b_ottimo)
        s = ValueTracker(6)
        targetP = always_redraw(
                    lambda: Dot(axes.c2p(9.5, s.get_value()), color = ORANGE)
                    )
        p_label = always_redraw(
                    lambda : MathTex(r"p", color = ORANGE).next_to(targetP, RIGHT)
                    )            
        line = always_redraw(
                lambda: Line(start=axes.c2p(0,b.get_value()), end=axes.c2p(10, 10*m.get_value()+b.get_value()), color=YELLOW)
                )
        l1 = line.copy()
        residuals = always_redraw(
                    lambda: VGroup(*[DashedLine(start=axes.c2p(_x,_y),
                                  end=axes.c2p(_x, _x*m.get_value()+b.get_value()), color=RED)
                             for _x,_y in zip(x,y)])
                             )

        squares = always_redraw(
                    lambda: VGroup(*[Square(side_length=r.get_length(), color=RED, fill_color=RED, fill_opacity=.6) \
                         .next_to(r, aligned_edge=LEFT, buff=0)
                           for r in residuals])
                           )
        etiquetas = VGroup(Tex(r"Precio", font_size = 24).next_to(Dot(axes.get_critical_point(DR)), RIGHT), Tex(r"Unidades vendidas", font_size = 24).next_to(Dot(axes.get_critical_point(UL)), UP).shift(0.5*RIGHT))
        questao1 = Tex(r"¿Qué pasará con las ventas si subimos el precio un poco más?", font_size =30).to_edge(UP)
        questao2 = Tex(r"¿Dónde debemos colocar ", r"p", r" según nuestros datos" ,r"?", font_size =30).to_edge(UP)
        nota = Tex(r"Mientras mayor el precio, menor la demanda", font_size = 30).next_to(questao2, DOWN)
        nota2 = Tex(r"Los datos se 'ajustan' a una recta decreciente", font_size = 30).next_to(nota, DOWN)
        questao2[1].set_color(ORANGE)
        questao3 = Tex(r"Pero... ¿A cuál?", font_size = 30).next_to(questao2, DOWN)
        nota3 = Tex(r"Queremos la que esté más cerca de los datos", font_size = 30).next_to(questao3, DOWN)
        l_eq = always_redraw(
                lambda: MathTex(r"L(x)",r"=", r"\alpha", r"x", r"+", r"\beta", color = YELLOW, font_size = 20).next_to(Dot(axes.c2p(9.8, 9.8*m.get_value()+b.get_value())), RIGHT, buff =0.1)
                )
        a2 = MathTex(r"=(x_2, y_2)").scale(0.5).next_to(points_labels[1], RIGHT, buff = 0.1)
        reso = MathTex(r"|\alpha x_2 + \beta - y_2|", color = RED, font_size = 24).next_to(residuals[1], LEFT)
        error = MathTex(r"\text{Error}=\sum_{i=1}^9|\alpha x_i + \beta -y_i|", color = RED, font_size =24).to_edge(UR)
        errorC = MathTex(r"\text{Error cuadrático}=\sum_{i=1}^9(\alpha x_i + \beta -y_i)^2", color = RED, font_size =24).to_edge(UR)
        nota4 = Tex(r"Queremos la que minimice el error", font_size = 30).next_to(questao3, DOWN)
        nota45 = Tex("Para minimizar las distancias, \\ podemos minimizar el cuadrado de las distancias", font_size =30).next_to(nota4, DOWN)
        box = BackgroundRectangle(nota45)
        nota5 = Tex(r"Queremos la que minimice el error cuadrático", font_size = 30).next_to(questao3, DOWN)
        
        #self.add(axes, points, line, residuals, squares)
        self.add(axes)
        self.play(AnimationGroup([FadeIn(p) for p in points], lag_ratio = 0.2), run_time =2)
        self.play(*[Write(_) for _ in points_labels])
        self.wait(2)
        self.play(AnimationGroup([Write(t) for t in etiquetas], lag_ratio =1.5))
        self.wait(2)
        self.play(FadeIn(VGroup(targetP, p_label)))
        self.wait()
        self.play(s.animate.increment_value(6), run_time = 3, rate_func = there_and_back)
        self.wait()
        self.play(Write(questao1))
        self.wait(2)
        self.play(ReplacementTransform(questao1, questao2))
        self.play(Indicate(points))
        self.wait(2)
        self.play(Write(nota))
        self.wait(2)
        self.play(Write(nota2))
        self.wait(2)
        self.play(Create(line))
        self.play(FadeOut(VGroup(questao2, nota)), nota2.animate.to_edge(UP))
        self.wait(2)
        self.play(Write(questao3))
        self.play(m.animate.increment_value(-0.75), run_time = 3, rate_func = there_and_back)
        self.wait()
        self.play(b.animate.increment_value(5), run_time = 3, rate_func = there_and_back)
        self.play(b.animate.increment_value(-3), run_time = 3, rate_func = there_and_back)
        self.wait(2)
        self.play(Write(nota3))
        self.wait(2)
        self.play(AnimationGroup([Create(r) for r in residuals], lag_ratio = 0.8))
        self.add(residuals) #No sabía que esto era necesario dx
        self.play(Write(l_eq))
        self.wait()
        self.play(Write(a2))
        self.wait()
        self.play(Create(reso))
        self.wait()
        self.play(Write(error), FadeOut(reso))
        self.wait()
        self.play(ReplacementTransform(nota3, nota4))
        self.play(m.animate.increment_value(-0.75), run_time = 2, rate_func = there_and_back)
        self.wait()
        self.play(b.animate.increment_value(5), run_time = 1, rate_func = there_and_back)
        self.play(b.animate.increment_value(-3), run_time = 1, rate_func = there_and_back)
        self.wait(2)
        self.play(FadeIn(box))
        self.play(Write(nota45))
        self.play(AnimationGroup([Create(_) for _ in squares]))
        self.play(ReplacementTransform(error, errorC))
        self.play(ReplacementTransform(nota4, nota5), FadeOut(VGroup(nota45, box)))
        self.wait()
        self.play(Create(SurroundingRectangle(nota5)))
        self.wait()

class E15(Scene):
    def construct(self):
        errorC = MathTex(r"\text{Error cuadrático}", r"=", r"\sum_{i=1}^n(\alpha x_i + \beta -y_i)^2")
        br = Brace(errorC[-1], DOWN, color = YELLOW)
        br_label = Tex(r"Depende de dos variables", color = YELLOW).next_to(br, DOWN)
        errorC1 = MathTex(r"EC(\alpha, \beta)", r"=", r"\sum_{i=1}^n(\alpha x_i + \beta -y_i)^2")
        errorC2 = MathTex(r"EC(\alpha)", r"=", r"\sum_{i=1}^n(\alpha x_i -y_i)^2")
        errorC3 = MathTex(r"EC(\alpha)", r"=", r"\sum_{i=1}^n(\alpha -a_i)^2")
        errorC4 = MathTex(r"EC(x)", r"=", r"\sum_{i=1}^n(x -a_i)^2")
        
        self.play(Write(errorC))
        self.wait(2)
        self.play(Create(br))
        self.play(Write(br_label))
        self.wait(2)
        self.play(FadeOut(VGroup(br, br_label)), ReplacementTransform(errorC, errorC1))
        self.wait()
        self.play(ReplacementTransform(errorC1, errorC2))
        self.wait()
        self.play(ReplacementTransform(errorC2, errorC3))
        self.wait()
        self.play(ReplacementTransform(errorC3, errorC4))
        self.wait()
        
        
class E2(Scene):
    def construct(self):        
        mini = Tex(r"Minimizar ", r"$\displaystyle EC(x)=\sum_{i=1}^n (x-a_i)^2$", font_size =36).to_edge(UP)
        der = Tex(r"Calculamos la derivada", font_size = 30, color = YELLOW).to_edge(UL).shift(1.5*DOWN+1*RIGHT)
        deriv = MathTex(r"EC'(x)" , r"=",  r"D_x" , r"\left(", r"\sum_{i=1}^n (x-a_i)^2", r"\right)", font_size = 30).next_to(der, DOWN).shift(0.5*RIGHT)
        deriv1 = MathTex(r"=", r"2 \sum_{i=1}^n (x-a_i)", font_size =30).next_to(deriv, DOWN).align_to(deriv[1], LEFT)
        paso2 = Tex(r"Calculamos los ceros de la derivada", font_size = 30, color = YELLOW).next_to(deriv1, DOWN).align_to(der, LEFT)
        ceros = MathTex(r"2 \sum_{i=1}^n (x-a_i)", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros1 = MathTex(r"\sum_{i=1}^n (x-a_i)", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros2 = MathTex(r"\sum_{i=1}^n x- \sum_{i=1}^n a_i", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros3 = MathTex(r"nx- \sum_{i=1}^n a_i", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros4 = MathTex(r"x = \frac{1}{n} \sum_{i=1}^n a_i", font_size =30).next_to(ceros2, DOWN)
        paso3 = Tex(r"Calculamos la segunda derivada", font_size = 30, color = YELLOW).align_to(der, UP).shift(2.5*RIGHT)
        dderiv = MathTex(r"EC''(x)" , r"=",  r"D_x" , r"\left(", r"2\sum_{i=1}^n (x-a_i)", r"\right)", font_size = 30).next_to(paso3, DOWN).shift(0.5*RIGHT)
        dderiv1 = MathTex(r"=", r"2 n", font_size =30).next_to(dderiv, DOWN).align_to(dderiv[1], LEFT)
        paso4 = Tex(r"Aplicamos el criterio de la segunda derivada", font_size = 30, color = YELLOW).next_to(dderiv1, DOWN).align_to(paso3, LEFT).align_to(paso2, DOWN)
        evalu = MathTex(r"E''\left(\frac{1}{n}\sum_{i=1}^n a_i\right)", r"=" , r"2n", r">", r"0", font_size = 30).next_to(paso4, DOWN)
        minv = Tex(r"Minimiza $EC$", font_size = 30).next_to(ceros4, RIGHT)
        media = Tex(r"La media aritmética minimiza $EC$", font_size =30).next_to(evalu, DOWN).align_to(minv, DOWN)
        
        self.play(Write(mini))
        self.wait(2)
        self.play(Write(der))
        self.wait()
        self.play(Write(deriv))
        self.wait()
        self.play(Write(deriv1[0]))
        self.play(ReplacementTransform(deriv[-2].copy(), deriv1[1]))
        self.wait(2)
        self.play(Write(paso2))
        self.wait()
        self.play(ReplacementTransform(deriv1.copy(), ceros[0]), Write(ceros[1:]))
        self.wait()
        self.play(ReplacementTransform(ceros, ceros1))
        self.wait()
        self.play(ReplacementTransform(ceros1, ceros2))
        self.wait()
        self.play(ReplacementTransform(ceros2, ceros3))
        self.wait()
        self.play(Write(ceros4))
        self.wait(2)
        self.play(Write(paso3))
        self.wait()
        self.play(Write(dderiv))
        self.wait()
        self.play(Write(dderiv1))
        self.wait(2)
        self.play(Write(paso4))
        self.wait()
        self.play(Write(evalu[:3]))
        self.wait(2)
        self.play(Write(evalu[3:]))
        self.wait()
        self.play(Write(minv))
        self.wait()
        self.play(Write(media))
        self.play(Create(SurroundingRectangle(media)))
        self.wait()

class E3(Scene):
    def construct(self):        
        teo = Tex(r"\textbf{Teorema.} Dado un conjunto de datos, la media aritmética de los datos minimiza el error cuadrático.", font_size =36)
        
        self.play(Create(SurroundingRectangle(teo)))
        self.play(Write(teo))
        self.wait(2)

class E4(Scene):
    def construct(self): 
        titulo = Tex(r"Problemas de optimización", color = YELLOW).to_edge(UP)
        mini = Tex(r"Minimizar ", r"$\displaystyle EC(x)=\sum_{i=1}^n (x-a_i)^2$", font_size =36).next_to(titulo, DOWN)
        maxi = Tex(r"Maximizar ", r"$\displaystyle EC(x)=\sum_{i=1}^n (x-a_i)^2$", font_size =36).next_to(titulo, DOWN)
        br = Brace(mini[1], direction = DOWN)
        br_label = Tex(r"Función objetivo", font_size = 24).next_to(br, DOWN)
        der = Tex(r"Calculamos la derivada", font_size = 30, color = YELLOW).to_edge(UL).shift(3*DOWN+1*RIGHT)
        deriv = MathTex(r"EC'(x)" , r"=",  r"D_x" , r"\left(", r"\sum_{i=1}^n (x-a_i)^2", r"\right)", font_size = 30).next_to(der, DOWN).shift(0.5*RIGHT)
        deriv1 = MathTex(r"=", r"2 \sum_{i=1}^n (x-a_i)", font_size =30).next_to(deriv, DOWN).align_to(deriv[1], LEFT)
        paso2 = Tex(r"Calculamos los ceros de la derivada", font_size = 30, color = YELLOW).next_to(deriv1, DOWN).align_to(der, LEFT)
        ceros = MathTex(r"2 \sum_{i=1}^n (x-a_i)", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros1 = MathTex(r"\sum_{i=1}^n (x-a_i)", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros2 = MathTex(r"\sum_{i=1}^n x- \sum_{i=1}^n a_i", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros3 = MathTex(r"nx- \sum_{i=1}^n a_i", r"=", r"0", font_size =30).next_to(paso2, DOWN)
        ceros4 = MathTex(r"x = \frac{1}{n} \sum_{i=1}^n a_i", font_size =30).next_to(ceros2, DOWN)
        paso3 = Tex(r"Calculamos la segunda derivada", font_size = 30, color = YELLOW).align_to(der, UP).shift(2.5*RIGHT)
        dderiv = MathTex(r"EC''(x)" , r"=",  r"D_x" , r"\left(", r"2\sum_{i=1}^n (x-a_i)", r"\right)", font_size = 30).next_to(paso3, DOWN).shift(0.5*RIGHT)
        dderiv1 = MathTex(r"=", r"2 n", font_size =30).next_to(dderiv, DOWN).align_to(dderiv[1], LEFT)
        paso4 = Tex(r"Aplicar el criterio de la segunda derivada", font_size = 30, color = YELLOW).next_to(dderiv1, DOWN).align_to(paso3, LEFT).align_to(paso2, DOWN)
        evalu = MathTex(r"E''\left(\frac{1}{n}\sum_{i=1}^n a_i\right)", r"=" , r"2n", r">", r"0", font_size = 30).next_to(paso4, DOWN)
        minv = Tex(r"Minimiza $EC$", font_size = 30).next_to(ceros4, RIGHT)
        media = Tex(r"La media aritmética minimiza $EC$", font_size =30).next_to(evalu, DOWN).align_to(minv, DOWN)
        
        self.play(Write(titulo  ))
        self.play(Write(mini))
        self.wait(2)
        self.play(Create(br))
        self.play(Write(br_label))
        self.wait()
        self.play(ReplacementTransform(mini, maxi))
        self.wait(2)
        self.play(AnimationGroup([Write(_) for _ in VGroup(der, paso2, paso3, paso4)], lag_ratio = 1))
        self.wait()