from manim import *
    
class E1(Scene):
    def construct(self):
        axes = NumberPlane()
        axes_labels = axes.get_axis_labels(x_label="x", y_label="y")
        p1 = Dot(axes.c2p(-2,0))
        p1_label = MathTex(r"a").next_to(p1, DOWN)
        p2 = Dot(axes.c2p(2,0))
        p2_label = MathTex(r"b").next_to(p2, DOWN)
        t= ValueTracker(0)
        s= ValueTracker(0)
        f = always_redraw (
                lambda: axes.plot(lambda x: -(x**2-4)*(1-t.get_value()), color = RED, x_range = [-2,2])
                )
        dibujo = VMobject()
        d = always_redraw(
            lambda: Dot().move_to(f.point_from_proportion(   s.get_value()  ))
        )
        texto1 = Tex(r"$f$ es continua en $[a,b]$ \\ y diferenciable en $(a,b)$", font_size = 28).to_edge(UL)
        texto2 = Tex(r"$f$ tiene un máximo y mínimo en $[a,b]$", font_size = 28).next_to(texto1, DOWN).align_to(texto1, LEFT)
        caso1 = Tex(r"Caso 1", font_size = 28).next_to(texto2, DOWN).align_to(texto1, LEFT)
        caso11 = Tex(r"$f$ tiene un máximo en $c \in (a,b)$", font_size = 28).next_to(caso1, DOWN).align_to(texto1, LEFT)
        fp = MathTex(r"f'(c)=0").next_to(caso11, DOWN).align_to(texto1, LEFT)
        c = Dot(ORIGIN, color = YELLOW)
        t1 = always_redraw(
                lambda: TangentLine(f, alpha =0.5, color = YELLOW).set_length(5)
                )
        g = axes.plot(lambda x: 0.5*(x**2-4)*(1-t.get_value()), color = RED, x_range = [-2,2])
        t2 = TangentLine(g, alpha =0.5, color = YELLOW).set_length(5)  
        c_label = MathTex(r"c", color = YELLOW).next_to(c, DOWN)
        caso2 = Tex(r"Caso 2", font_size = 28).next_to(fp, DOWN).align_to(texto1, LEFT)
        caso22 = Tex(r"$f$ tiene un mínimo en $c \in (a,b)$", font_size = 28).next_to(caso2, DOWN).align_to(texto1, LEFT)
        fp1 = fp.copy().next_to(caso22, DOWN).align_to(texto1, LEFT)
        caso3 = Tex(r"Caso 3", font_size = 28).next_to(fp1, DOWN).align_to(texto1, LEFT)
        caso33 = Tex(r"$f$ tiene un máximo y mínimo en $a$ o en $b$", font_size = 28).next_to(caso3, DOWN).align_to(texto1, LEFT)       
        l = Line(p1.get_center(), p2.get_center(), color = RED)
        fp2 = fp.copy().next_to(caso33, DOWN).align_to(texto1, LEFT)
        
        
        self.add(axes, axes_labels)
        self.wait(1.5)
        self.play(FadeIn(VGroup(p1, p1_label, p2, p2_label)))
        self.add(dibujo, d)
        self.wait()
        dibujo.add_updater(lambda x: x.become(f.get_subcurve(0, s.get_value()) ))
        self.play(s.animate.set_value(1), run_time = 4)
        self.add(f)
        self.remove(dibujo, d)
        self.wait(2)
        self.play(t.animate.set_value(1), run_time = 4)
        self.wait(2)
        self.play(t.animate.set_value(0.5))
        self.wait()
        self.play(Create(BackgroundRectangle(texto1)))
        self.play(Write(texto1))
        self.wait()
        self.play(Create(BackgroundRectangle(texto2)))
        self.play(Write(texto2))
        self.wait()
        self.play(Create(BackgroundRectangle(caso1)))
        self.play(Write(caso1))
        self.wait()
        self.play(Create(BackgroundRectangle(caso11)))
        self.play(Write(caso11))
        self.wait()
        self.play(FadeIn(VGroup(c, c_label)))
        self.wait()
        self.play(Create(t1))
        self.wait()
        self.play(Create(BackgroundRectangle(fp)))
        self.play(Write(fp))
        self.wait()
        self.play(Create(BackgroundRectangle(caso2)))
        self.play(Write(caso2))
        self.wait()
        self.play(Create(BackgroundRectangle(caso22)))
        self.play(Write(caso22))
        self.play(ReplacementTransform(f, g), ReplacementTransform(t1, t2))
        self.wait()
        self.play(Create(BackgroundRectangle(fp1)))
        self.play(Write(fp1))
        self.wait()
        self.play(Create(BackgroundRectangle(caso3)))
        self.play(Write(caso3))
        self.wait()
        self.play(Create(BackgroundRectangle(caso33)))
        self.play(Write(caso33))
        self.play(ReplacementTransform(g, l), FadeOut(t2))
        self.wait()
        self.play(Create(BackgroundRectangle(fp2)))
        self.play(Write(fp2))
        self.wait()
        self.play(*[Create(SurroundingRectangle(_)) for _ in VGroup(fp, fp1, fp2)])
        self.wait()
        
class E2(Scene):
    def construct(self):        
        teo = Tex(r"\textbf{Teorema}. (\textit{Rolle}). Sea $f$ una función continua en $[a,b]$, diferenciable en $(a,b)$ y $f(a)=f(b)$ \\ Entonces, existe $c \in (a,b)$ tal que $f'(c)=0$", font_size = 36)
        
        self.play(Create(SurroundingRectangle(teo)))
        self.play(Write(teo), run_time =3)
        self.wait(3)

class E3(Scene):
    def construct(self):        
        axes = Axes(x_range=(-1,10,1),
                    y_range=(-1,20,1),
                    axis_config={"include_numbers": False, "include_tip": False}).shift(0.5*LEFT)
        axes_labels = axes.get_axis_labels()

        p1 = axes.c2p(1,5)
        p2 = axes.c2p(8, 15)
        
        p1d = Dot(p1)
        p1d_label = MathTex(r"a").next_to(p1d, DOWN).shift(0.25*RIGHT)
        p2d = Dot(p2)
        p2d_label = MathTex(r"b").next_to(p2d, DOWN).shift(0.25*RIGHT)
        bezier = CubicBezier(p1, p1 + 2* RIGHT+2*UP, p2 -3 * RIGHT+2*UP, p2, color = BLUE)
        tange = VGroup(*[TangentLine(bezier, 0.1+i*0.1, color = YELLOW).set_length(8) for i in range(9)]) #Esto fue para muestrear al ojo
        tval = TangentLine(bezier, 0.59, color = YELLOW).set_length(12)
        line = Line(p1, p2, color = RED).set_length(10)
        l1 = axes.get_lines_to_point(p1)
        l2 = axes.get_lines_to_point(p2)
        f_label = MathTex(r"f(x)", color = BLUE, font_size=24).next_to(bezier, UP).shift(0.5*UP)
        l_eq = MathTex(r"S(x) = \frac{f(b)-f(a)}{b-a}(x-a)+f(a)", color = RED, font_size = 24).next_to(line, DOWN).shift(1*UP)
        distances = VGroup(*[Line(line.point_from_proportion(0.1+i*0.1), bezier.point_from_proportion(0.1+i*0.1), color = ORANGE) for i in range(9)])
        d_eq = MathTex(r"d(x)= f(x)-S(x)", font_size = 24, color = ORANGE).to_edge(UR)
        d_a = MathTex(r"d(a)= f(a)-S(a)", r"=0", font_size = 24).next_to(d_eq, DOWN).align_to(d_eq, LEFT)
        d_b = MathTex(r"d(b)= f(b)-S(b)", r"=0", font_size = 24).next_to(d_a, DOWN).align_to(d_eq, LEFT)
        rolle = Tex(r"Por el teorema de Rolle", font_size = 24, color = YELLOW).next_to(d_b, DOWN)
        rolle2 = Tex(r"Existe $c \in (a,b):$", font_size = 24).next_to(rolle, DOWN)
        rolle3 = MathTex(r"d'(c)=0", font_size = 24).next_to(rolle2, DOWN).align_to(d_eq, LEFT)
        sectan = MathTex(r"f'(c)", r"-", r"S'(c)", r"=", r"0", font_size = 24).next_to(rolle3, DOWN).align_to(d_eq, LEFT)
        sectan1 = MathTex(r"f'(c)", r"=", r"S'(c)", font_size = 24).next_to(rolle3, DOWN).align_to(d_eq, LEFT)
        sPrima = MathTex(r"S'(x) = \frac{f(b)-f(a)}{b-a}", font_size = 24, color = RED).next_to(l_eq, DOWN).align_to(l_eq, LEFT)
        sectan2 = MathTex(r"f'(c)", r"=", r"\frac{f(b)-f(a)}{b-a}", font_size = 24).next_to(sectan1, DOWN).align_to(d_eq, LEFT)
        ces = axes.get_lines_to_point(bezier.point_from_proportion(0.59), color = YELLOW)
        c = MathTex(r"c", color = YELLOW).move_to((bezier.point_from_proportion(0.59)[0],axes.c2p(0,0)[1],0))
              
        self.add(axes, axes_labels)
        self.wait()
        self.play(FadeIn(p1d, p1d_label, p2d, p2d_label)) 
        self.wait(2)    
        self.play(Create(bezier))    
        self.wait()
        self.play(Create(line)) 
        self.wait()    
        #self.play(AnimationGroup([Create(t) for t in tange], lag_ratio =1   ))
        #self.play(Create(tval))
        self.play(Create(VGroup(l1, l2)))
        self.wait()
        self.play(Write(f_label), Write(l_eq))
        self.wait(2)
        self.play(AnimationGroup([Create(l) for l in distances], lag_ratio = 0.5))
        self.play(Uncreate(distances))
        self.wait(2)
        self.play(Write(d_eq))
        self.wait()
        self.play(Write(d_a[0]))
        self.wait()
        self.play(Write(d_a[1]))
        self.wait()
        self.play(Write(d_b[0]))
        self.wait()
        self.play(Write(d_b[1]))
        self.wait()
        self.play(AnimationGroup([Write(t) for t in VGroup(rolle, rolle2, rolle3)], lag_ratio = 1))
        self.wait()
        self.play(Write(sectan))
        self.wait()
        self.play(TransformMatchingTex(sectan, sectan1))
        self.wait()
        self.play(Write(sPrima))
        self.wait()
        self.play(Write(sectan2))
        self.wait()
        self.play(Create(SurroundingRectangle(sectan2)))
        self.wait()
        self.play(Create(VGroup(ces, c)))
        self.play(Create(tval))
        self.wait(2)