from manim   import *

class E1(Scene):
    def construct(self):
        texto_normal = Tex(r"Determine todas las asíntotas de la siguiente función ",color=YELLOW).to_edge(UP)
        self.play(Write(texto_normal))
        self.wait(1)
        ecuacion= MathTex(r"f(x)=x^{\frac{1}{x}}").next_to(texto_normal,DOWN).shift(DOWN)
        self.play(Write(ecuacion))
        self.wait(1)
        ecuacion_1= MathTex(r"f(x)=x^{\frac{1}{x}ln(x)}").next_to(ecuacion,DOWN).shift(DOWN)
        self.play(Write(ecuacion_1))
        self.wait(1)
        texto_nor = MathTex(r"\mathrm{dom} f =(0,+\infty) ",color=YELLOW).next_to(ecuacion_1,DOWN).shift(DOWN)
        self.play(Write(texto_nor))
        self.wait(1)
        self.play(FadeOut(VGroup(texto_normal,ecuacion,ecuacion_1,texto_nor)))
        self.wait(1)
        ecuacion_2= MathTex(r"f(x)=e^{\frac{1}{x}}, x>0", color= YELLOW).to_edge(LEFT+UP)
        self.play(Write(ecuacion_2))
        self.wait(1)
        texto1 = Tex(r"$f$ es continua en todo su dominio")
        texto2 = Tex(r"ya que es la composición de")
        texto3 = Tex(r"funciones continuas.")
        texto4 = Tex(r"Por tanto, $f$ solamente")
        texto5 = Tex(r"podria tener una asíntota")
        texto6 = Tex(r"vertical $x=0$.")
        parrafo=VGroup(texto1,texto2,texto3,texto4, texto5,texto6).arrange(DOWN,aligned_edge=LEFT)
        self.play(AnimationGroup(*[Write(mobj) for mobj in parrafo.to_edge(LEFT)],lag_ratio=1))
        self.wait(1)
        ecu_1= MathTex(r"\lim_{x \to 0^{+}}f(x)=\lim_{x \to 0^{+}}e^{\frac{1}{x}\ln(x)}", color= YELLOW)
        ecu_2= MathTex(r"=e^{\frac{1}{0^{+}}ln(0^{+})}", color= YELLOW, )
        ecu_3= MathTex(r"=e^{(+\infty)(-\infty)}", color= YELLOW)
        ecu_4= MathTex(r"=e^{-\infty}", color= YELLOW)
        ecu_5= MathTex(r"=0", color= YELLOW)
        parrafo1=VGroup(ecu_1,ecu_2,ecu_3,ecu_4).arrange(DOWN,aligned_edge=LEFT)
        self.play(AnimationGroup(*[Write(mobj) for mobj in parrafo1.to_edge(RIGHT)],lag_ratio=1))
        self.wait(1)
        ecu_5.move_to(ecu_4.get_center())

        # Reemplazamos ecu_4 por ecu_5 usando ReplacementTransform
        self.play(ReplacementTransform(ecu_4, ecu_5.align_to(ecu_3,LEFT)))
        self.wait(2)
        self.play(FadeOut(VGroup(parrafo, parrafo1, ecu_5)))
        self.wait(1)
        texto7= Tex(r"Por tanto, $f$ no tiene asíntotas verticales")
        recto=SurroundingRectangle(texto7)
        self.play(Create(recto),Write(texto7))
        self.wait(2)
        self.play(FadeOut(VGroup(recto, texto7)))        
        self.wait(2)
        tex1 = Tex(r"Como $\mathrm{dom} f = (0,+\infty)$,")
        tex2 = Tex(r"estudiemos el comportamiento")
        tex3 = Tex(r"de $f$ cuando $x \to +\infty$")
        parrafo3=VGroup(tex1,tex2,tex3).arrange(DOWN,aligned_edge=LEFT)
        self.play(AnimationGroup(*[Write(mobj) for mobj in parrafo3.to_edge(LEFT)]))
        self.wait(1)
        ec_1= MathTex(r"\lim_{x \to +\infty}f(x)=\lim_{x \to +\infty}e^{\frac{1}{x}\ln(x)}", color= YELLOW)
        ec_2= MathTex(r"=e^{\lim\limits_{x \to +\infty} \frac{\ln(x)}{x}}", color= YELLOW)
        ec_3= MathTex(r"=e^{\frac{+\infty}{+\infty}}", color= YELLOW)
        parr1=VGroup(ec_1,ec_2).arrange(DOWN,aligned_edge=LEFT)
        self.play(AnimationGroup(*[Write(mobj) for mobj in parr1.to_edge(RIGHT)],lag_ratio=1))
        self.wait(1)
        ec_3.move_to(ec_2.get_center())
        self.play(ReplacementTransform(ec_2, ec_3.align_to(ec_1,LEFT)))
        self.wait(2)
        ec_2.move_to(ec_3.get_center())
        self.play(ReplacementTransform(ec_3, ec_2.align_to(ec_1,LEFT)))
        self.wait(2)
        ec_4=MathTex(r"=e^{\lim\limits_{x \to +\infty} \frac{\frac{d}{dx}\ln(x)}{\frac{d}{dx}x}}").next_to(ec_2,DOWN).align_to(ec_2,LEFT)
        self.play(Write(ec_4))
        self.wait(2)
        ec_5=MathTex(r"=e^{\lim\limits_{x \to +\infty} \frac{1}{x}}").next_to(ec_4,DOWN).align_to(ec_4,LEFT)
        self.play(Write(ec_5))
        self.wait(2)
        ec_6=MathTex(r"=e^{\frac{1}{\infty}}", color=YELLOW).next_to(ec_5,DOWN).align_to(ec_5,LEFT)
        self.play(Write(ec_6))
        self.wait(2)
        ec_7=MathTex(r"=e^{0}", color=YELLOW).move_to(ec_6).align_to(ec_5, LEFT)
        self.play(ReplacementTransform(ec_6, ec_7))
        self.wait(2)
        ec_8=MathTex(r"=1", color=YELLOW).move_to(ec_7).align_to(ec_5,LEFT)
        self.play(ReplacementTransform(ec_7, ec_8))
        self.wait(2)
        self.play(FadeOut(VGroup(parrafo3, parr1,ec_4,ec_5,ec_8)))
        self.wait(2)
        self.play(Write(ecuacion_2.move_to(ORIGIN).shift(UP)))
        self.wait(2)
        trac1 = Tex(r"La función $f$ tiene una única asíntota")
        trac2 = Tex(r"horizontal $y=1$, pero no tiene")
        trac3 = Tex(r"ninguna asíntota vertical ni oblicua.")
        rafo3=VGroup(trac1,trac2,trac3).arrange(DOWN,aligned_edge=LEFT)
        self.play(AnimationGroup(*[Write(mobj) for mobj in rafo3.next_to(ecuacion_2,DOWN).to_edge(ORIGIN)],lag_ratio=1))
        self.wait(1)
        self.play(FadeOut(VGroup(ecuacion_2, rafo3)))
        self.wait(2)
        plane = NumberPlane(background_line_style={"stroke_opacity": 0.4}) 
        q_graph = plane.plot(lambda x: x**(1/x), x_range=[0.05, 12], color=BLUE)
        #max_x = 2.718 
        #max_y = max_x**(1/max_x)
        q_dot = Dot(plane.c2p(0, 0), color=BLACK, stroke_color=YELLOW,stroke_width=1)
        q_label = MathTex(r"f(x)=x^{1/x}").set_color(YELLOW).next_to(q_graph, UP).shift(LEFT)
        x_label = MathTex("x").next_to(plane.x_axis, RIGHT)  
        y_label = MathTex("y").next_to(plane.y_axis, UP)  
        dashed_line_x = DashedLine(start=plane.c2p(0, 1), end=plane.c2p(12,1), color=YELLOW)
        self.play(Create(plane))
        self.wait(1)
        self.play(Create(q_graph), Create(q_dot), Write(q_label))
        self.wait(1)
        self.play(Write(x_label), Write(y_label))
        self.wait(1)
        self.play(Create(dashed_line_x))
        self.wait(2)
